import { BankProfile } from '../types';

export const BANK_PROFILES: BankProfile[] = [
  // ── 1. BANCA TRADICIONAL NACIONAL ──────────────────────────────────
  {
    id: 'caixabank',
    name: 'CaixaBank / imagin',
    shortName: 'CaixaBank',
    badgeColor: '#007eae',
    delimiters: [';', ','],
    signatureHeaders: ['fecha', 'concepto', 'importe', 'saldo'],
    dateColumns: ['fecha', 'f. valor', 'fecha operación', 'fecha valor'],
    conceptColumns: ['concepto', 'descripción', 'movimiento', 'detalle'],
    amountColumns: ['importe', 'importe eur', 'cantidad'],
    balanceColumns: ['saldo', 'saldo eur', 'saldo final'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'santander',
    name: 'Banco Santander',
    shortName: 'Santander',
    badgeColor: '#ec0000',
    delimiters: [';', ','],
    signatureHeaders: ['fecha operación', 'fecha valor', 'concepto', 'importe eur'],
    dateColumns: ['fecha operación', 'fecha valor', 'fecha operacion', 'fecha'],
    conceptColumns: ['concepto', 'descripción', 'detalle movimiento'],
    amountColumns: ['importe eur', 'importe', 'movimiento eur'],
    balanceColumns: ['saldo eur', 'saldo', 'disponible'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'bbva',
    name: 'BBVA',
    shortName: 'BBVA',
    badgeColor: '#004481',
    delimiters: [';', '\t', ','],
    signatureHeaders: ['fecha', 'concepto', 'movimiento', 'importe', 'divisa'],
    dateColumns: ['fecha', 'f. operación', 'fecha valor'],
    conceptColumns: ['concepto', 'movimiento', 'descripción', 'observaciones'],
    amountColumns: ['importe', 'movimiento', 'cargo/abono'],
    balanceColumns: ['saldo', 'saldo contable'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'sabadell',
    name: 'Banco Sabadell',
    shortName: 'Sabadell',
    badgeColor: '#006dff',
    delimiters: [';', ','],
    signatureHeaders: ['f. operación', 'f. valor', 'concepto', 'importe'],
    dateColumns: ['f. operación', 'f. operacion', 'fecha', 'f. valor'],
    conceptColumns: ['concepto', 'descripción movimiento', 'detalle'],
    amountColumns: ['importe', 'importe eur'],
    balanceColumns: ['saldo', 'saldo resultante'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'bankinter',
    name: 'Bankinter',
    shortName: 'Bankinter',
    badgeColor: '#ff6600',
    delimiters: [';', ','],
    signatureHeaders: ['fecha', 'descripción', 'cargo/abono', 'saldo'],
    dateColumns: ['fecha', 'fecha movimiento', 'fecha valor'],
    conceptColumns: ['descripción', 'concepto', 'detalle'],
    amountColumns: ['cargo/abono', 'importe', 'cantidad'],
    balanceColumns: ['saldo', 'saldo actual'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'abanca',
    name: 'Abanca',
    shortName: 'Abanca',
    badgeColor: '#0039a6',
    delimiters: [';', ','],
    signatureHeaders: ['fecha operación', 'concepto', 'importe'],
    dateColumns: ['fecha operación', 'fecha', 'f. operación'],
    conceptColumns: ['concepto', 'descripción', 'observaciones'],
    amountColumns: ['importe', 'importe eur'],
    balanceColumns: ['saldo'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'unicaja',
    name: 'Unicaja Banco',
    shortName: 'Unicaja',
    badgeColor: '#008752',
    delimiters: [';', ','],
    signatureHeaders: ['fecha contable', 'concepto', 'importe'],
    dateColumns: ['fecha contable', 'fecha operación', 'fecha'],
    conceptColumns: ['concepto', 'descripción'],
    amountColumns: ['importe', 'importe eur'],
    balanceColumns: ['saldo'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'kutxabank',
    name: 'Kutxabank',
    shortName: 'Kutxabank',
    badgeColor: '#c2002f',
    delimiters: [';', ','],
    signatureHeaders: ['fecha', 'concepto', 'cargo / abono'],
    dateColumns: ['fecha', 'fecha valor'],
    conceptColumns: ['concepto', 'detalle'],
    amountColumns: ['cargo / abono', 'importe'],
    balanceColumns: ['saldo'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'ibercaja',
    name: 'Ibercaja',
    shortName: 'Ibercaja',
    badgeColor: '#e30613',
    delimiters: [';', ','],
    signatureHeaders: ['fecha', 'concepto', 'importe euros'],
    dateColumns: ['fecha', 'fecha valor'],
    conceptColumns: ['concepto', 'texto'],
    amountColumns: ['importe euros', 'importe'],
    balanceColumns: ['saldo euros', 'saldo'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },

  // ── 2. BANCA DIGITAL Y ONLINE ─────────────────────────────────────
  {
    id: 'ing',
    name: 'ING España',
    shortName: 'ING',
    badgeColor: '#ff6200',
    delimiters: [';', ','],
    signatureHeaders: ['fecha', 'descripción', 'categoría', 'importe'],
    dateColumns: ['fecha', 'f. valor'],
    conceptColumns: ['descripción', 'concepto', 'categoría'],
    amountColumns: ['importe', 'importe (€)', 'importe eur'],
    balanceColumns: ['saldo'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'openbank',
    name: 'Openbank',
    shortName: 'Openbank',
    badgeColor: '#d6001c',
    delimiters: [';', ','],
    signatureHeaders: ['fecha', 'concepto', 'importe'],
    dateColumns: ['fecha', 'fecha valor'],
    conceptColumns: ['concepto', 'descripción'],
    amountColumns: ['importe', 'importe eur'],
    balanceColumns: ['saldo'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'myinvestor',
    name: 'MyInvestor',
    shortName: 'MyInvestor',
    badgeColor: '#2b2d42',
    delimiters: [';', ','],
    signatureHeaders: ['fecha', 'tipo', 'concepto', 'importe'],
    dateColumns: ['fecha', 'fecha valor'],
    conceptColumns: ['concepto', 'tipo', 'descripción'],
    amountColumns: ['importe', 'importe eur', 'movimiento'],
    balanceColumns: ['saldo'],
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'n26',
    name: 'N26 Bank',
    shortName: 'N26',
    badgeColor: '#36a18b',
    delimiters: [',', ';'],
    signatureHeaders: ['date', 'payee', 'amount (eur)'],
    dateColumns: ['date', 'fecha'],
    conceptColumns: ['payee', 'beneficiario', 'payment reference', 'descripción'],
    amountColumns: ['amount (eur)', 'amount', 'importe'],
    balanceColumns: [],
    dateFormat: 'YYYY-MM-DD',
    decimalSeparator: '.',
    thousandsSeparator: ','
  },
  {
    id: 'revolut',
    name: 'Revolut',
    shortName: 'Revolut',
    badgeColor: '#19b4ff',
    delimiters: [',', ';'],
    signatureHeaders: ['type', 'product', 'started date', 'completed date', 'description', 'amount'],
    dateColumns: ['completed date', 'started date', 'date', 'fecha completada', 'fecha de inicio'],
    conceptColumns: ['description', 'descripción', 'beneficiario'],
    amountColumns: ['amount', 'importe'],
    balanceColumns: ['balance', 'saldo'],
    dateFormat: 'auto',
    decimalSeparator: '.',
    thousandsSeparator: ','
  },

  // ── 3. BROKERS Y CUENTAS REMUNERADAS ──────────────────────────────
  {
    id: 'traderepublic',
    name: 'Trade Republic',
    shortName: 'Trade Republic',
    badgeColor: '#000000',
    delimiters: [',', ';'],
    signatureHeaders: ['date', 'type', 'title', 'amount'],
    dateColumns: ['date', 'timestamp', 'fecha'],
    conceptColumns: ['title', 'type', 'description', 'concepto'],
    amountColumns: ['amount', 'importe', 'value'],
    balanceColumns: ['balance'],
    dateFormat: 'auto',
    decimalSeparator: 'auto',
    thousandsSeparator: 'auto'
  },
  {
    id: 'scalable',
    name: 'Scalable Capital (Baader Bank)',
    shortName: 'Scalable',
    badgeColor: '#111827',
    delimiters: [';', ','],
    signatureHeaders: ['valutadatum', 'buchungsdatum', 'buchungstext', 'betrag'],
    dateColumns: ['buchungsdatum', 'valutadatum', 'fecha', 'date'],
    conceptColumns: ['buchungstext', 'concepto', 'description'],
    amountColumns: ['betrag', 'importe', 'amount'],
    balanceColumns: ['saldo', 'balance'],
    dateFormat: 'auto',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'degiro',
    name: 'Degiro',
    shortName: 'Degiro',
    badgeColor: '#f59e0b',
    delimiters: [',', ';'],
    signatureHeaders: ['fecha', 'hora', 'producto', 'descripción', 'cambio', 'saldo'],
    dateColumns: ['fecha', 'date'],
    conceptColumns: ['descripción', 'producto', 'concepto', 'description'],
    amountColumns: ['cambio', 'variación', 'importe'],
    balanceColumns: ['saldo'],
    dateFormat: 'DD-MM-YYYY',
    decimalSeparator: ',',
    thousandsSeparator: '.'
  },
  {
    id: 'ibkr',
    name: 'Interactive Brokers',
    shortName: 'IBKR',
    badgeColor: '#dc2626',
    delimiters: [',', ';'],
    signatureHeaders: ['statement', 'header', 'data', 'accountinformation'],
    dateColumns: ['date/time', 'settle date', 'trade date', 'fecha'],
    conceptColumns: ['description', 'symbol', 'concepto'],
    amountColumns: ['amount', 'net amount', 'total', 'importe'],
    balanceColumns: ['ending cash'],
    dateFormat: 'YYYY-MM-DD',
    decimalSeparator: '.',
    thousandsSeparator: ','
  }
];

export const FALLBACK_KEYWORDS = {
  date: ['fecha', 'date', 'f.operación', 'f.valor', 'dia', 'día', 'completed', 'started'],
  concept: ['concepto', 'descripción', 'descripcion', 'concept', 'description', 'payee', 'movimiento', 'detalle', 'beneficiario', 'title', 'texto', 'operación'],
  amount: ['importe', 'amount', 'cargo', 'abono', 'movimiento', 'cantidad', 'betrag', 'valor', 'cambio', 'total'],
  income: ['abono', 'ingreso', 'haber', 'credit'],
  expense: ['cargo', 'gasto', 'debe', 'debit']
};
